enum TransType {
    TRANS_ACA = 0,
    TRANS_ACR,
    TRANS_aPAY, // account auto pay
    TRANS_aDEP, // account deposit
    TRANS_aWDR, // account withdrawal
    TRANS_ENQ,
    TRANS_CAN,
    TRANS_PAY,
    TRANS_REF,
    TRANS_CVI,
    TRANS_CVC,
    TRANS_CVP,
    TRANS_DEP,
    TRANS_WDR,
    TRANS_HVP, // high value pay
    TRANS_eBF, // eft bank debit
    TRANS_eBB, // eft bank balance
    TRANS_eCVI,
    TRANS_eTBD,
    TRANS_eTBW,
    TRANS_eTBB, // eft TB balance
    TRANS_WIN,
    TRANS_PLA,
    TRANS_QIN,
    TRANS_QPL,
    TRANS_WP,
    TRANS_DBL,
    TRANS_6UP,
    TRANS_6WN,
    TRANS_TCE,
    TRANS_DQ,
    TRANS_TBL,
    TRANS_DT,
    TRANS_AWN,
    TRANS_APL,
    TRANS_AWP,
    TRANS_AQIN,
    TRANS_QTT,
    TRANS_QAD,
    TRANS_TT,
    TRANS_AQP,
    TRANS_AUT,
    TRANS_FCT,
    TRANS_QQP,
    TRANS_TRI,
    TRANS_HAD,
    TRANS_HDC,
    TRANS_CRS,
    TRANS_CRSP,
    TRANS_TTG,
    TRANS_HFT,
    TRANS_HFTP,
    TRANS_AHAD,
    TRANS_HIL,
    TRANS_OOE,
    TRANS_HCSP,
    TRANS_THFP,
    TRANS_FGS,
    TRANS_HHAD,
    TRANS_AHHAD,
    TRANS_MK6,
    TRANS_ACRS,
    TRANS_AHIL,
    TRANS_AOOE,
    TRANS_ATTG,
    TRANS_AHFT,
    TRANS_HFMP6,
    TRANS_HFMP8,
    TRANS_DHCP,
    TRANS_CHP,
    TRANS_TOFP,
    TRANS_ADTP,
    TRANS_GPW,
    TRANS_GPF,
    TRANS_AGPW,
    TRANS_AGPF,
    TRANS_SPCM,
    TRANS_SPCT,
    TRANS_TPS,
    TRANS_AHDC,
    TRANS_AUP,
    TRANS_STB,
    TRANS_FF,
    TRANS_FHAD,
    TRANS_TQL,
    TRANS_JKC,
    TRANS_FTS,
    TRANS_NTS,
    TRANS_ETS,
    TRANS_FHLO,
    TRANS_FCRS,
    TRANS_CHLO,
    TRANS_ACW,
    TRANS_CWA,
    TRANS_CWB,
    TRANS_CWC,
    TRANS_IWN,
    TRANS_MAX,
    TRANS_FLT,
    TRANS_TNC,
}

enum CustomerType {
    CUST_TB = 0,
    CUST_ESC,
    CUST_PAYOUT,
    CUST_QRC,
}

enum CustomerStatus {
    ACCOUNT_NONE = 0,
    ACCOUNT_INITED,
    ACCOUNT_ACCESSED,
    ACCOUNT_RELEASED,
    ACCOUNT_COMPLETED,
}

enum CallFlagType {
    CALL_FLAG_NONE = 0xff,
    CALL_FLAG_TX_BOCC = 0x00,
    CALL_FLAG_TX_HOTLINE = 0x10,
    CALL_FLAG_TX_ESCADMIN = 0x30,
    CALL_FLAG_DIVI_FORFEIT = 0x40,
    CALL_FLAG_TX_SS = 0x50,
    CALL_FLAG_TX_8000 = 0x60,
    CALL_FLAG_UPGRADE = 0x70,
}

enum ErtType {
    NONE = 0,
    IS,
    TB,
    ALL,
}

enum ReleaseCodeType {
    RELEASE_NORMAL = 0,
    RELEASE_CARD_REMOVED = 1,
}

enum AccountType {
    ACC_NONE = -1,
    ACC_NOMINATED,
    ACC_PAN,
    ACC_SAN1,
    ACC_SAN2,
    ACC_OTHER,
}

enum NBAType {
    NBA_NONE = 0,
    NBA_PRI,
    NBA_SEC,
}

const TransArray: Array<string> = [
    'ACA',
    'ACR',
    'APAY',
    'DEP',
    'WDR',
    'ENQ',
    'CAN',
    'PAY',
    'REF',
    'CVI',
    'CVC',
    'CVP',
    'DEP',
    'WDR',
    'HVP',
    'eBF',
    'eBB',
    'eCVI',
    'eTBD',
    'eTBW',
    'eTBB',
    'WIN',
    'PLA',
    'QIN',
    'QPL',
    'W-P',
    'DBL',
    '6UP',
    '6WN',
    'TCE',
    'DQ ',
    'TBL',
    'D-T',
    'AWN',
    'APL',
    'AWP',
    'AQN',
    'QTT',
    'QAD',
    'T-T',
    'AQP',
    'AUT',
    'FCT',
    'QQP',
    'TRI',
    'HAD',
    'HDC',
    'CRS',
    'CRSP',
    'TTG',
    'HFT',
    'HFTP',
    'ALUP HAD',
    'HILO',
    'OOE',
    'HCSP',
    'THFP',
    'FGS',
    'HHAD',
    'ALUP HHAD',
    'MK6',
    'ALUP CRS',
    'ALUP HIL',
    'ALUP OOE',
    'ALUP TTG',
    'ALUP HFT',
    'HFMP',
    'HFMP',
    'DHCP',
    'CHP',
    'TOFP',
    'ADTP',
    'GPW',
    'GPF',
    'ALUP GPW',
    'ALUP GPF',
    'SPC (M)',
    'SPC (T)',
    'TPS',
    'ALUP HDC',
    'ALUP',
    'STB',
    'FF ',
    'FHAD',
    'TQL',
    'JKC',
    'FTS',
    'NTS',
    'ETS',
    'FHLO',
    'FCRS',
    'CHLO',
    'ACW',
    'CWA',
    'CWB',
    'CWC',
    'IWN',
    'XXXX',
    'FLT',
    'TNC',
];

enum CustomerLength {
    TB_ACCOUNT_LENGTH = 8,
    ESC_ACCOUNT_LENGTH = 16,
    TB_SEC_CODE_LENGTH = 6,
    MAX_PIN_LENGTH = 12,
    NBA_LENGTH = 13,
    REGISTRATION_LENGTH = 8,
    EWALLET_ACCOUNT_LENGTH = 8,
}

export {
    ErtType,
    TransType,
    CustomerType,
    CustomerStatus,
    CallFlagType,
    ReleaseCodeType,
    AccountType,
    NBAType,
    TransArray,
    CustomerLength,
};
